# 服务名
spring:
  application:
    name: beacon-test
  # nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # datasource
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://11.0.1.3:3306/beacon_cloud?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
# 端口号
server:
  port: 2000

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true